//
// TrackSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TrackSource: JSONEncodable {

    public enum Source: String { 
        case Soundcloud = "SOUNDCLOUD"
    }
    
    public var id: Int?
    public var owner: SourceAccount?
    public var source: Source?
    public var uri: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["owner"] = self.owner?.encodeToJSON()
        nillableDictionary["source"] = self.source?.rawValue
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
