//
// SourcesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension EigenMusikAPI {
    
    public class SourcesAPI: APIBase {
    
        /**
         
         addSource
         
         - POST /rest/source/add/{source}
         - addSource
         - examples: [{output=none}]
         
         - parameter source: (path) source
         - parameter code: (body) code
         - parameter principal: (body) principal

         - returns: RequestBuilder<String> 
         */
        public class func addSourceUsingPOST(source source: String, code: String, principal: Principal?) -> RequestBuilder<String> {
            var path = "/rest/source/add/{source}"
            path = path.stringByReplacingOccurrencesOfString("{source}", withString: "\(source)", options: .LiteralSearch, range: nil)
            let URLString = EigenMusikAPI.basePath + path
            
            let parameters = principal?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<String>.Type = EigenMusikAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
