//
// TracksAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension EigenMusikAPI {
    
    public class TracksAPI: APIBase {
    
        /**
         
         getTracks
         
         - GET /rest/tracks
         - getTracks
         - examples: [{output=none}]
         
         - parameter principal: (body) principal
         - parameter pageable: (body) pageable

         - returns: RequestBuilder<Page«Track»> 
         */
        public class func getTracksUsingGET(principal principal: Principal?, pageable: Pageable?) -> RequestBuilder<Page«Track»> {
            let path = "/rest/tracks"
            let URLString = EigenMusikAPI.basePath + path
            
            let parameters = pageable?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<Page«Track»>.Type = EigenMusikAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
        /**
         
         getStreamUrl
         
         - GET /rest/tracks/ /stream/{trackId}
         - getStreamUrl
         - examples: [{output=none}]
         
         - parameter trackId: (path) trackId
         - parameter principal: (body) principal
         - parameter pageable: (body) pageable

         - returns: RequestBuilder<TrackStreamUrl> 
         */
        public class func getStreamUrlUsingGET(trackId trackId: Int, principal: Principal?, pageable: Pageable?) -> RequestBuilder<TrackStreamUrl> {
            var path = "/rest/tracks/ /stream/{trackId}"
            path = path.stringByReplacingOccurrencesOfString("{trackId}", withString: "\(trackId)", options: .LiteralSearch, range: nil)
            let URLString = EigenMusikAPI.basePath + path
            
            let parameters = pageable?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<TrackStreamUrl>.Type = EigenMusikAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
