//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension EigenMusikAPI {
    
    public class UserAPI: APIBase {
    
        /**
         
         getMe
         
         - GET /user/me
         - getMe
         - examples: [{output=none}]
         
         - parameter principal: (body) principal

         - returns: RequestBuilder<Inline_response_200> 
         */
        public class func getMeUsingGET(principal principal: Principal?) -> RequestBuilder<Inline_response_200> {
            let path = "/user/me"
            let URLString = EigenMusikAPI.basePath + path
            
            let parameters = principal?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<Inline_response_200>.Type = EigenMusikAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
        /**
         
         register
         
         - POST /user/register
         - register
         - examples: [{output=none}]
         
         - parameter user: (body) user

         - returns: RequestBuilder<Inline_response_200> 
         */
        public class func registerUsingPOST(user user: User) -> RequestBuilder<Inline_response_200> {
            let path = "/user/register"
            let URLString = EigenMusikAPI.basePath + path
            
            let parameters = user.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<Inline_response_200>.Type = EigenMusikAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
